-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/CommunityRequests/sql/community_requests.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE community_requests (
  cr_page INT NOT NULL,
  cr_status INT NOT NULL,
  cr_type INT NOT NULL,
  cr_title TEXT NOT NULL,
  cr_audience TEXT DEFAULT NULL,
  cr_other_project TEXT DEFAULT NULL,
  cr_focus_area INT DEFAULT NULL,
  cr_actor BIGINT NOT NULL,
  cr_timestamp TIMESTAMPTZ NOT NULL,
  PRIMARY KEY(cr_page)
);

CREATE INDEX cr_timestamp ON community_requests (cr_timestamp);

CREATE INDEX cr_title ON community_requests (cr_title);

CREATE UNIQUE INDEX cr_page ON community_requests (cr_page);
