-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/CommunityRequests/sql/community_requests_focus_areas.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE community_requests_focus_areas (
  crfa_page INT NOT NULL,
  crfa_title TEXT NOT NULL,
  crfa_status INT NOT NULL,
  crfa_timestamp TIMESTAMPTZ NOT NULL,
  PRIMARY KEY(crfa_page)
);

CREATE INDEX crfa_title ON community_requests_focus_areas (crfa_title);

CREATE INDEX crfa_timestamp ON community_requests_focus_areas (crfa_timestamp);

CREATE UNIQUE INDEX crfa_page ON community_requests_focus_areas (crfa_page);
