-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/CommunityRequests/sql/community_requests_projects.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE community_requests_projects (
  crp_id SERIAL NOT NULL,
  crp_project INT NOT NULL,
  crp_request INT NOT NULL,
  PRIMARY KEY(crp_id)
);

CREATE UNIQUE INDEX crp_project_request ON community_requests_projects (crp_project, crp_request);
