-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/CommunityRequests/sql/community_requests_votes.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE community_requests_votes (
  crv_id SERIAL NOT NULL,
  crv_request INT DEFAULT NULL,
  crv_focus_area INT DEFAULT NULL,
  crv_vote INT NOT NULL,
  crv_actor BIGINT NOT NULL,
  crv_timestamp TIMESTAMPTZ NOT NULL,
  PRIMARY KEY(crv_id)
);

CREATE INDEX crv_request ON community_requests_votes (crv_request);

CREATE INDEX crv_focus_area ON community_requests_votes (crv_focus_area);

CREATE UNIQUE INDEX crv_request_focus_area_actor ON community_requests_votes (
  crv_request, crv_focus_area, crv_actor
);
