-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/abstractSchemaChanges/patch-communityrequests_wishes_translations-drop-cwt_other_project.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE communityrequests_wishes_translations
  DROP crt_other_project;
