-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/abstractSchemaChanges/patch-communityrequests_wishes_tags-key-renames.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
DROP INDEX crp_project_wish;

ALTER TABLE communityrequests_tags
  DROP CONSTRAINT communityrequests_tags_pkey;

ALTER TABLE communityrequests_tags
  ADD crtg_tag INT NOT NULL;

ALTER TABLE communityrequests_tags
  ADD crtg_wish INT NOT NULL;

ALTER TABLE communityrequests_tags
  DROP crp_project;

ALTER TABLE communityrequests_tags
  DROP crp_wish;

CREATE INDEX crtg_tag_wish ON communityrequests_tags (crtg_tag, crtg_wish);

ALTER TABLE communityrequests_tags
  ADD PRIMARY KEY (crtg_wish, crtg_tag);
