-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE communityrequests_entities (
  cr_page INT NOT NULL,
  cr_entity_type SMALLINT DEFAULT 0 NOT NULL,
  cr_status INT NOT NULL,
  cr_wish_type INT DEFAULT NULL,
  cr_focus_area INT DEFAULT NULL,
  cr_actor BIGINT DEFAULT NULL,
  cr_vote_count INT DEFAULT 0 NOT NULL,
  cr_base_lang TEXT NOT NULL,
  cr_created TIMESTAMPTZ NOT NULL,
  cr_updated TIMESTAMPTZ NOT NULL,
  PRIMARY KEY(cr_page)
);

CREATE INDEX cr_created ON communityrequests_entities (cr_created);

CREATE INDEX cr_updated ON communityrequests_entities (cr_updated);

CREATE INDEX cr_vote_count ON communityrequests_entities (cr_vote_count);


CREATE TABLE communityrequests_translations (
  crt_entity INT NOT NULL,
  crt_lang TEXT NOT NULL,
  crt_title TEXT NOT NULL,
  PRIMARY KEY(crt_lang, crt_entity)
);

CREATE INDEX crt_lang_title ON communityrequests_translations (crt_lang, crt_title);


CREATE TABLE communityrequests_tags (
  crtg_tag INT NOT NULL,
  crtg_entity INT NOT NULL,
  PRIMARY KEY(crtg_entity, crtg_tag)
);

CREATE INDEX crtg_tag_entity ON communityrequests_tags (crtg_tag, crtg_entity);


CREATE TABLE communityrequests_counters (
  crc_type SMALLINT NOT NULL,
  crc_value INT NOT NULL,
  PRIMARY KEY(crc_type)
);
