-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/CommunityRequests/sql/community_requests_phab_tasks.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/community_requests_phab_tasks (
  crpt_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  crpt_task_id INTEGER UNSIGNED NOT NULL,
  crpt_request INTEGER UNSIGNED NOT NULL
);

CREATE INDEX crpt_task_request ON /*_*/community_requests_phab_tasks (crpt_task_id, crpt_request);
