-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/CommunityRequests/sql/community_requests_projects.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/community_requests_projects (
  crp_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  crp_project INTEGER UNSIGNED NOT NULL,
  crp_request INTEGER UNSIGNED NOT NULL
);

CREATE UNIQUE INDEX crp_project_request ON /*_*/community_requests_projects (crp_project, crp_request);
