-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/CommunityRequests/sql/community_requests_focus_areas.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/community_requests_focus_areas (
  crfa_page INTEGER UNSIGNED NOT NULL,
  crfa_title BLOB NOT NULL,
  crfa_status INTEGER UNSIGNED NOT NULL,
  crfa_timestamp BLOB NOT NULL,
  PRIMARY KEY(crfa_page)
);

CREATE INDEX crfa_title ON /*_*/community_requests_focus_areas (crfa_title);

CREATE INDEX crfa_timestamp ON /*_*/community_requests_focus_areas (crfa_timestamp);

CREATE UNIQUE INDEX crfa_page ON /*_*/community_requests_focus_areas (crfa_page);
