-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/CommunityRequests/sql/community_requests.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/community_requests (
  cr_page INTEGER UNSIGNED NOT NULL,
  cr_status INTEGER UNSIGNED NOT NULL,
  cr_type INTEGER UNSIGNED NOT NULL,
  cr_title BLOB NOT NULL,
  cr_audience BLOB DEFAULT NULL,
  cr_other_project BLOB DEFAULT NULL,
  cr_focus_area INTEGER UNSIGNED DEFAULT NULL,
  cr_actor BIGINT UNSIGNED NOT NULL,
  cr_timestamp BLOB NOT NULL,
  PRIMARY KEY(cr_page)
);

CREATE INDEX cr_timestamp ON /*_*/community_requests (cr_timestamp);

CREATE INDEX cr_title ON /*_*/community_requests (cr_title);

CREATE UNIQUE INDEX cr_page ON /*_*/community_requests (cr_page);
