-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/abstractSchemaChanges/patch-communityrequests_wishes_tags-key-renames.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TEMPORARY TABLE /*_*/__temp__communityrequests_tags AS
SELECT
FROM /*_*/communityrequests_tags;

DROP TABLE /*_*/communityrequests_tags;


CREATE TABLE /*_*/communityrequests_tags (
  crtg_tag INTEGER UNSIGNED NOT NULL,
  crtg_wish INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(crtg_wish, crtg_tag)
);

INSERT INTO /*_*/communityrequests_tags ()
SELECT
FROM
  /*_*/__temp__communityrequests_tags;

DROP TABLE /*_*/__temp__communityrequests_tags;

CREATE INDEX crtg_tag_wish ON /*_*/communityrequests_tags (crtg_tag, crtg_wish);
