-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/abstractSchemaChanges/patch-communityrequests_wishes_translations-drop-cwt_other_project.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TEMPORARY TABLE /*_*/__temp__communityrequests_wishes_translations AS
SELECT
  crt_wish,
  crt_lang,
  crt_title
FROM /*_*/communityrequests_wishes_translations;

DROP TABLE /*_*/communityrequests_wishes_translations;


CREATE TABLE /*_*/communityrequests_wishes_translations (
  crt_wish INTEGER UNSIGNED NOT NULL,
  crt_lang BLOB NOT NULL,
  crt_title BLOB NOT NULL,
  PRIMARY KEY(crt_lang, crt_wish)
);

INSERT INTO /*_*/communityrequests_wishes_translations (crt_wish, crt_lang, crt_title)
SELECT
  crt_wish,
  crt_lang,
  crt_title
FROM
  /*_*/__temp__communityrequests_wishes_translations;

DROP TABLE /*_*/__temp__communityrequests_wishes_translations;

CREATE INDEX crt_lang_title ON /*_*/communityrequests_wishes_translations (crt_lang, crt_title);
