-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/communityrequests_entities (
  cr_page INTEGER UNSIGNED NOT NULL,
  cr_entity_type SMALLINT DEFAULT 0 NOT NULL,
  cr_status INTEGER UNSIGNED NOT NULL,
  cr_wish_type INTEGER UNSIGNED DEFAULT NULL,
  cr_focus_area INTEGER UNSIGNED DEFAULT NULL,
  cr_actor BIGINT UNSIGNED DEFAULT NULL,
  cr_vote_count INTEGER UNSIGNED DEFAULT 0 NOT NULL,
  cr_base_lang BLOB NOT NULL,
  cr_created BLOB NOT NULL,
  cr_updated BLOB NOT NULL,
  PRIMARY KEY(cr_page)
);

CREATE INDEX cr_created ON /*_*/communityrequests_entities (cr_created);

CREATE INDEX cr_updated ON /*_*/communityrequests_entities (cr_updated);

CREATE INDEX cr_vote_count ON /*_*/communityrequests_entities (cr_vote_count);


CREATE TABLE /*_*/communityrequests_translations (
  crt_entity INTEGER UNSIGNED NOT NULL,
  crt_lang BLOB NOT NULL,
  crt_title BLOB NOT NULL,
  PRIMARY KEY(crt_lang, crt_entity)
);

CREATE INDEX crt_lang_title ON /*_*/communityrequests_translations (crt_lang, crt_title);


CREATE TABLE /*_*/communityrequests_tags (
  crtg_tag INTEGER UNSIGNED NOT NULL,
  crtg_entity INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(crtg_entity, crtg_tag)
);

CREATE INDEX crtg_tag_entity ON /*_*/communityrequests_tags (crtg_tag, crtg_entity);


CREATE TABLE /*_*/communityrequests_counters (
  crc_type SMALLINT NOT NULL,
  crc_value INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(crc_type)
);
