-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/CommunityRequests/sql/community_requests_focus_areas.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/community_requests_focus_areas (
  crfa_page INT UNSIGNED NOT NULL,
  crfa_title VARBINARY(255) NOT NULL,
  crfa_status INT UNSIGNED NOT NULL,
  crfa_timestamp BINARY(14) NOT NULL,
  INDEX crfa_title (crfa_title),
  INDEX crfa_timestamp (crfa_timestamp),
  UNIQUE INDEX crfa_page (crfa_page),
  PRIMARY KEY(crfa_page)
) /*$wgDBTableOptions*/;
