-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/CommunityRequests/sql/community_requests_votes.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/community_requests_votes (
  crv_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  crv_request INT UNSIGNED DEFAULT NULL,
  crv_focus_area INT UNSIGNED DEFAULT NULL,
  crv_vote INT UNSIGNED NOT NULL,
  crv_actor BIGINT UNSIGNED NOT NULL,
  crv_timestamp BINARY(14) NOT NULL,
  INDEX crv_request (crv_request),
  INDEX crv_focus_area (crv_focus_area),
  UNIQUE INDEX crv_request_focus_area_actor (
    crv_request, crv_focus_area, crv_actor
  ),
  PRIMARY KEY(crv_id)
) /*$wgDBTableOptions*/;
