-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/CommunityRequests/sql/community_requests_phab_tasks.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/community_requests_phab_tasks (
  crpt_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  crpt_task_id INT UNSIGNED NOT NULL,
  crpt_request INT UNSIGNED NOT NULL,
  INDEX crpt_task_request (crpt_task_id, crpt_request),
  PRIMARY KEY(crpt_id)
) /*$wgDBTableOptions*/;
