-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/abstractSchemaChanges/patch-communityrequests_wishes_tags-key-renames.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
DROP INDEX crp_project_wish ON /*_*/communityrequests_tags;

DROP INDEX `primary` ON /*_*/communityrequests_tags;

ALTER TABLE /*_*/communityrequests_tags
  ADD crtg_tag INT UNSIGNED NOT NULL,
  ADD crtg_wish INT UNSIGNED NOT NULL,
  DROP crp_project,
  DROP crp_wish;

CREATE INDEX crtg_tag_wish ON /*_*/communityrequests_tags (crtg_tag, crtg_wish);

ALTER TABLE /*_*/communityrequests_tags
  ADD PRIMARY KEY (crtg_wish, crtg_tag);
