-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/communityrequests_wishes (
  cr_page INT UNSIGNED NOT NULL,
  cr_type INT UNSIGNED NOT NULL,
  cr_status INT UNSIGNED NOT NULL,
  cr_focus_area INT UNSIGNED DEFAULT NULL,
  cr_actor BIGINT UNSIGNED NOT NULL,
  cr_vote_count INT UNSIGNED DEFAULT 0 NOT NULL,
  cr_base_lang VARBINARY(35) NOT NULL,
  cr_created BINARY(14) NOT NULL,
  cr_updated BINARY(14) NOT NULL,
  INDEX cr_created (cr_created),
  INDEX cr_updated (cr_updated),
  INDEX cr_vote_count (cr_vote_count),
  PRIMARY KEY(cr_page)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/communityrequests_focus_areas (
  crfa_page INT UNSIGNED NOT NULL,
  crfa_status INT UNSIGNED NOT NULL,
  crfa_vote_count INT UNSIGNED DEFAULT 0 NOT NULL,
  crfa_base_lang VARBINARY(35) NOT NULL,
  crfa_created BINARY(14) NOT NULL,
  crfa_updated BINARY(14) NOT NULL,
  INDEX crfa_created (crfa_created),
  INDEX crfa_updated (crfa_updated),
  INDEX crfa_vote_count (crfa_vote_count),
  PRIMARY KEY(crfa_page)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/communityrequests_wishes_translations (
  crt_wish INT UNSIGNED NOT NULL,
  crt_lang VARBINARY(35) NOT NULL,
  crt_title VARBINARY(255) NOT NULL,
  crt_other_project VARBINARY(255) DEFAULT NULL,
  INDEX crt_lang_title (crt_lang, crt_title),
  PRIMARY KEY(crt_lang, crt_wish)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/communityrequests_focus_areas_translations (
  crfat_focus_area INT UNSIGNED NOT NULL,
  crfat_lang VARBINARY(35) NOT NULL,
  crfat_title VARBINARY(255) NOT NULL,
  crfat_short_description MEDIUMBLOB NOT NULL,
  INDEX crfat_lang_title (crfat_lang, crfat_title),
  PRIMARY KEY(crfat_lang, crfat_focus_area)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/communityrequests_projects (
  crp_project INT UNSIGNED NOT NULL,
  crp_wish INT UNSIGNED NOT NULL,
  INDEX crp_project_wish (crp_project, crp_wish),
  PRIMARY KEY(crp_wish, crp_project)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/communityrequests_phab_tasks (
  crpt_task_id INT UNSIGNED NOT NULL,
  crpt_wish INT UNSIGNED NOT NULL,
  INDEX crpt_task_wish (crpt_task_id, crpt_wish),
  PRIMARY KEY(crpt_wish, crpt_task_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/communityrequests_counters (
  crc_type TINYINT(1) NOT NULL,
  crc_value INT UNSIGNED NOT NULL,
  PRIMARY KEY(crc_type)
) /*$wgDBTableOptions*/;
