-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/communityrequests_entities (
  cr_page INT UNSIGNED NOT NULL,
  cr_entity_type TINYINT(1) DEFAULT 0 NOT NULL,
  cr_status INT UNSIGNED NOT NULL,
  cr_wish_type INT UNSIGNED DEFAULT NULL,
  cr_focus_area INT UNSIGNED DEFAULT NULL,
  cr_actor BIGINT UNSIGNED DEFAULT NULL,
  cr_vote_count INT UNSIGNED DEFAULT 0 NOT NULL,
  cr_base_lang VARBINARY(35) NOT NULL,
  cr_created BINARY(14) NOT NULL,
  cr_updated BINARY(14) NOT NULL,
  INDEX cr_created (cr_created),
  INDEX cr_updated (cr_updated),
  INDEX cr_vote_count (cr_vote_count),
  PRIMARY KEY(cr_page)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/communityrequests_translations (
  crt_entity INT UNSIGNED NOT NULL,
  crt_lang VARBINARY(35) NOT NULL,
  crt_title VARBINARY(255) NOT NULL,
  INDEX crt_lang_title (crt_lang, crt_title),
  PRIMARY KEY(crt_lang, crt_entity)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/communityrequests_tags (
  crtg_tag INT UNSIGNED NOT NULL,
  crtg_entity INT UNSIGNED NOT NULL,
  INDEX crtg_tag_entity (crtg_tag, crtg_entity),
  PRIMARY KEY(crtg_entity, crtg_tag)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/communityrequests_counters (
  crc_type TINYINT(1) NOT NULL,
  crc_value INT UNSIGNED NOT NULL,
  PRIMARY KEY(crc_type)
) /*$wgDBTableOptions*/;
